"""Type stubs for FortiZTP models."""

from typing import Any, Iterator, Optional, overload
from .types import DeviceV2Data


class FortiZTPDevice:
    """
    Wrapper for individual device objects with typed attribute access.
    
    Provides both attribute and dictionary access to device fields.
    """
    
    _data: dict[str, Any]
    
    def __init__(self, data: dict[str, Any]) -> None: ...
    
    # Typed attribute access for known device fields
    @property
    def deviceSN(self) -> str: ...
    @property
    def deviceType(self) -> str: ...
    @property
    def provisionStatus(self) -> str: ...
    @property
    def provisionTarget(self) -> Optional[str]: ...
    @property
    def region(self) -> Optional[str]: ...
    @property
    def externalControllerSn(self) -> Optional[str]: ...
    @property
    def externalControllerIp(self) -> Optional[str]: ...
    @property
    def platform(self) -> Optional[str]: ...
    @property
    def firmwareProfile(self) -> Optional[str]: ...
    @property
    def fortiManagerOid(self) -> Optional[int]: ...
    @property
    def scriptOid(self) -> Optional[int]: ...
    @property
    def useDefaultScript(self) -> Optional[bool]: ...
    @property
    def provisioningTimestamp(self) -> Optional[int]: ...
    @property
    def provisioningCompleteTimestamp(self) -> Optional[int]: ...
    @property
    def provisionSubStatus(self) -> Optional[str]: ...
    @property
    def message(self) -> Optional[str]: ...
    
    def __getitem__(self, key: str) -> Any: ...
    def __repr__(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...


class FortiZTPResponse:
    """
    Structured wrapper for FortiZTP API responses.
    
    Provides clean attribute access to API response data with metadata.
    """
    
    _data: dict[str, Any]
    _http_status_code: Optional[int]
    _response_time: Optional[float]
    _request_info: Optional[dict[str, Any]]
    
    def __init__(
        self,
        data: dict[str, Any],
        http_status_code: Optional[int] = None,
        response_time: Optional[float] = None,
        request_info: Optional[dict[str, Any]] = None,
    ) -> None: ...
    
    @property
    def http_status_code(self) -> Optional[int]: ...
    @property
    def response_time(self) -> Optional[float]: ...
    @property
    def raw(self) -> dict[str, Any]: ...
    @property
    def json(self) -> dict[str, Any]: ...
    @property
    def request_info(self) -> Optional[dict[str, Any]]: ...
    @property
    def request_method(self) -> Optional[str]: ...
    @property
    def request_url(self) -> Optional[str]: ...
    @property
    def request_params(self) -> Optional[dict[str, Any]]: ...
    @property
    def request_data(self) -> Optional[dict[str, Any]]: ...
    
    # Data field access
    @property
    def data(self) -> Any: ...
    @property
    def total(self) -> Optional[int]: ...
    @property
    def hasCache(self) -> Optional[bool]: ...
    
    def dict(self) -> dict[str, Any]: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> Iterator[FortiZTPDevice]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...


__all__: list[str]
